### ISSUE TITLE
NBC

### ISSUE THREAD

**Issue by island8889** [newswap/misc.newswap.org#48]
New Business Coin (NBC) is the world's first Distributed Autonomous Co-rich Organization (DACO), dedicated to achieving global wealth sharing through decentralized financial management. NBC integrates cutting-edge blockchain technology, quantum AI systems, and forward-looking economic models to build a transparent, fair, and efficient financial ecosystem. Through an innovative social credit rating system and ecosystem incentive mechanisms, NBC drives global economic innovation, creating a new era of shared wealth.

Website: https://newbusinesscoin.com/

Address：0x9143491de28168B9Aa5F72dE48026a8b1e9AA91f

![image](https://github.com/newswap/misc.newswap.org/assets/173425444/e3379bac-9d04-417c-b730-9d21b36bb54c)

**Comment by mengguang** [comment]
已经更新。
